services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=InfluencerSponsorship'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=InfluencerSponsorshipApplication'
    ports:
      - '5432'
